title: Blanks
description: A good starting point for building a Jekyll site
highlighter: pygments
sass:
    sass_dir: _sass
    style: expanded
permalink: :title
exclude: [README.md, Rakefile, node_modules, Gruntfile.js, package.json, deploy-stage, deploy-prod]
