title: Blanks
description: A good starting point for building a Jekyll site
markdown: redcarpet
highlighter: pygments
sass:
    sass_dir: _sass
    style: compressed
permalink: :title
exclude: [README.md, Rakefile]

# use this to insert a list of keywords in a <meta> tag in "html-head.html"

# keywords:
#   - yaml
#   - list
#   - "of keywords"

# Glynn FTP - https://github.com/dmathieu/glynn
# This is a really simple way to deploy your site with one command.
# You'll need to Install the gem first.
# Just delete this part if you are using something else to deploy.

# ftp_host: 'yoursite.com'
# ftp_dir: 'public_html/your-directory'
# ftp_passive: false
# ftp_username: 'your_ftp_user_name'
